<?php

function popup_order_form($form, &$form_state) {

  $form['actions'] = array(
    '#type' => 'actions',
  );
 $arg=arg(1);
$form['nid'] = array(
'#type' => 'value', 
'#value' => $arg,
);
  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Booking'),
	'#validated'=> true,
    '#ajax' => array(
      'callback' => 'popup_order_form_ajax_callback',
	  'progress' => array('type' => 'throbber'),
    ),
	 );
  $form['#attached']['library'][] = array('system', 'ui.dialog');
$form['#attached']['library'][] = array('system', 'effects.fade');
 $form['#attached']['css'][] = drupal_get_path('module', 'popup_order') . '/popup_order.css';

  return $form;
}
 
function popup_order_form_ajax_callback($form, $form_state) {
	$nid = $form_state['values']['nid'];
  $form = drupal_get_form('popup_order_more_form',$nid);
$node = node_load($nid);
$result = field_view_field('node', $node, 'field_num_id', array('default'));
$id =$result['#object']->field_num_id['und'][0]['taxonomy_term']->name;

  $commands = array();

  $commands[] = ajax_command_append('body', '<div id="popup"></div>');
  $commands[] = ajax_command_html('#popup', render($form));
  $commands[] = ajax_command_invoke('#popup', 'dialog',array(
												array(
												'modal' => TRUE,
												'show'=> "fade", 
												'resizable'=> false,
												'dialogClass'=>"booking",
												'title'=>t('Booking of the apartment ID @', array('@'=>$id)), 
												'width'=>'500' )));
  $commands[] = ajax_command_invoke('popup_order[name="action"]', 'click');
 
  return array('#type' => 'ajax', '#commands' => $commands);
 

 }

function popup_order_more_form($form, &$form_state,$nid) {
$form['#attached']['js'][] = drupal_get_path('module', 'popup_order') . '/popup_order.js';

$form['#attached']['library'][] = array('system', 'ui.datepicker');
 
$form['#prefix'] = '<div id="after-wrapper">';
  $form['#suffix'] = '</div>';


  $form['popup_order_surname'] = array (
	'#type' => 'textfield',
	'#title'=> t('Surname'),
	'#attributes'=>array('id' => 'surname'),
    '#size' => 12,
	);

	$form['popup_order_name'] = array (
	 '#type' => 'textfield',
    '#title'=> t('Name'),
	'#attributes'=>array('id' => 'name'),
	'#size' => 10,
	);


$form["date_zas"] = array (
	'#type' => 'textfield',
	'#size' => 15,
	'#title' => t('Check-in date'),
	'#attributes' =>array('placeholder' => t('Select a date'),'id'=>'from'),
	);
	$form["date_vys"] = array (
	'#type' => 'textfield',
	'#size' => 15,
	'#title' => t('Check-out date'),
	'#attributes' =>array('placeholder' => t('Select a date'), 'id'=>'to'),
	);



$form["hour_zas"] = array (
	'#type' => 'textfield',
	'#title'=>t('Check-in time'),
		'#maxlength' => 5,
		'#size'=> 10,
	'#default_value'=> '19:00',
	'#attributes'=>array('id' => 'hour'),
		'#attributes' =>array('placeholder' => '19:00'),
		);
if(isset($form_state['values']['hour_zas'])) {
$form['hour_zas']['#default_value']=$form_state['values']['hour_zas'];
}

$form["kolvo_zas"] = array (
	'#type' => 'select',
	'#title' => t('Number of guests'),
	'#default_value'=> '0',
	'#options' => array(
      0=> t('Select'),
	  1=> t('1'),
      2 => t('2'),
	  3 => t('3'),
	  4 => t('4 and more'),
	  ),
	);
if (isset($form_state['values']["kolvo_zas"])) {
$form["kolvo_zas"]['#default_value'] = $form_state['values']["kolvo_zas"];}

$form["transfer"] = array (
	'#type' => 'radios',
	'#title' => t('Transfer service'),
	'#options' => array('yes' => t('Need'), 'no' => t('Not needed')),
	'#default_value'=> 'no',
    );


$node = node_load($nid);

$result = field_view_field('node', $node, 'field_num_id', array('default'));
$output =$result['#object']->field_num_id['und'][0]['taxonomy_term']->name;

$kzt = field_view_field('node', $node, 'field_prkzt', array('label'=>'hidden','type'=>'kzt_value'));
$kzt_value = $kzt[0]['#markup'];

$form['prc'] = array (
	'#type'=>'item',
	'#title'=> $kzt_value,
);

$dollor_value  = field_view_field('node', $node, 'field_prusd', array('label'=>'hidden','type'=>'usd_value'));

$dollor = $dollor_value[0]['#markup'];
$rub_value  = field_view_field('node', $node, 'field_prrub',array('label'=>'hidden','type'=>'rub_value'));

$rub = $rub_value[0]['#markup'];

$fv = field_get_items('node', $node, 'field_etaj');
foreach ($fv as $field) {
$etaj = $field['value'];
}
$spalm = field_get_items('node', $node, 'field_spal_mest');
foreach ($spalm as $field) {
$spal = $field['value'];
}
	

$fiv = field_get_items('node', $node, 'field_etajnost');
foreach ($fiv as $field) {
$etajnost = $field['value'];
}


$class_k = field_view_field('node', $node, 'field_class_kv', array('default'));
$class_kvart =$class_k['#object']->field_class_kv['und'][0]['taxonomy_term']->name;

$images = field_get_items('node',$node, 'field_gallery');
if (is_array($images)){
$img = field_view_value('node', $node, 'field_gallery', $images[0], array(
		'type' => 'image',
		'settings' => array(
					'image_style' => 'special_p',
					),
		)
	);
}
	
	$form['image'] = array (
		'#type'=>'markup',
		'#prefix'=>'<div>',
		'#markup'=> $img,
		'#suffix'=>'</div>'
		);
		
		
		


$form['idkvart'] = array (
	'#type'=>'item',
	'#title'=> $output,
);




$form['class'] = array (
	'#type' =>'item',
	'#title' => $class_kvart
);
$form['kvartira'] = array (
	'#type' =>'item',
	'#title' => $kzt_value
);

	
$form['etaj'] = array (
	'#type'=>'item',
	'#title'=> $etaj
	);
$form['etajnost'] = array (
	'#type'=>'item',
	'#title'=> $etajnost
	);
$form['spalm'] = array (
	'#type'=>'item',
	'#title'=> $spal
	);
	
$form['pricedollor']= array (
		'#type'=>'item',
		'#title'=> $dollor,
);
$form['pricerub']= array (
		'#type'=>'item',
		'#title'=> $rub,
);

	$form ["email"] = array (
	'#type' => 'textfield',
	'#title' => t('Email'),
	'#size' => 17,
	'#attributes' =>array('placeholder' => t('E-mail address'))
	);
	$form["phone"] = array (
	'#type' => 'textfield',
	'#title' => t('Phone'),
	'#size' => 12,
	'#attributes' =>array('placeholder' => t('E.g., 87015594434')),
	);
$form ['other_info'] = array (
	'#type' => 'textarea',
	'#title' => t('Additional information'),	
	'#cols'=> 40,
	'#rows'=> 3,
	);

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
	 '#ajax' => array(
        'callback' => 'popup_order_more_form_ajax_callback',
        'wrapper' => 'after-wrapper',
		'progress' => array('type' => 'none'),
      ),
  );
$count = mt_rand(1000,9999);
  $form['counter'] = array(
    '#type' => 'hidden',
    '#value' => $count,
  );
  
  $form['close'] = array(
    '#type' => 'button',
    '#value' => t('Close'),
	 '#ajax' => array(
        'callback' => 'popup_order_more_form_close_ajax_callback',
		'progress' => array('type' => 'none'),
  ),
  );

  return $form;
}


function popup_order_more_form_close_ajax_callback($form, $form_state) {
  
  $commands = array();

  $commands[] = ajax_command_invoke('#popup', 'dialog',array('close'));
    $commands[] = ajax_command_invoke('input[name="close"]', 'click');
 
  return array('#type' => 'ajax', '#commands' => $commands);
 

 }



function popup_order_more_form_ajax_callback($form, $form_state) {
$namevalid = trim($form_state['values']['popup_order_name']);

if($namevalid == '') {   

$commands = array();
  $commands[]=  ajax_command_alert(t('Please enter Your Name'));
  $commands[] = ajax_command_invoke('input[name="submit"]', 'click');	
 
  return array('#type' => 'ajax', '#commands' => $commands);
  }
if (empty($form_state['values']['date_zas'])) {
  $commands = array();
  $commands[]=  ajax_command_alert(t('Please enter check-in date'));
  $commands[] = ajax_command_invoke('input[name="submit"]', 'click');  
   return array('#type' => 'ajax', '#commands' => $commands);
}
if (empty($form_state['values']['date_vys'])) {
  $commands = array();
  $commands[]=  ajax_command_alert(t('Please enter check-out date'));
  $commands[] = ajax_command_invoke('input[name="submit"]', 'click');  
   return array('#type' => 'ajax', '#commands' => $commands);
}

$phonevalid=trim($form_state['values']['phone']);
if(strlen($phonevalid) < 7){
$commands = array();
  $commands[]=  ajax_command_alert(t('The phone number have at least 7 digits'));
  $commands[] = ajax_command_invoke('input[name="submit"]', 'click');	
 
  return array('#type' => 'ajax', '#commands' => $commands);
}
if (!preg_match('/^[0-9()-xX\s]+$/', (string) $phonevalid)) {
    $commands = array();
  $commands[]=  ajax_command_alert(t('The phone number can only have digits, parenthesis and dashes.'));
  $commands[] = ajax_command_invoke('input[name="submit"]', 'click');	
 
  return array('#type' => 'ajax', '#commands' => $commands);
}

 
if(!valid_email_address($form_state['values']['email'])){
$commands = array();
  $commands[]=  ajax_command_alert(t('The email address does not appear to be valid.'));
  $commands[] = ajax_command_css('input[name="date_vys[date]"]', array('border-color' => 'red'));
  $commands[] = ajax_command_invoke('input[name="submit"]', 'click');	
 
  return array('#type' => 'ajax', '#commands' => $commands);
}


  return $form;
}
function popup_order_theme()
{ 
return array
	(
		'popup_order_more_form' => array
		(
			'render element' => 'form'
		),
	);
	}
	
 function popup_order_more_form_validate($form, &$form_state) {
 }
function theme_popup_order_more_form($variables)
{
	// Isolate the form definition form the $variables array
	$form = $variables['form'];
	$output = '';

	$output .= '<fieldset class="apartdesc"><legend>'.t('Apartment').'</legend>';
	$output .='<div class="booking-desc-wrap">';
	$output .= '<div class="book-img-wrap">'. drupal_render($form['image']['#markup']).'</div>';
	unset($form['image']);
	$output.= '<div class="kv-desc-small"><table><tr><td rowspan="6"><div class="popular-price">';
	$output .= strip_tags(drupal_render($form['kvartira']),'<span>');
	$output .= strip_tags(drupal_render($form['pricedollor']), "<span>");
	$output .= strip_tags(drupal_render($form['pricerub']), "<span>");
	$output .= '</div></td></tr><tr><td class="boldtd"><span> ID: </span>';
	$output .= strip_tags(drupal_render($form['idkvart']));
	$output .='</td></tr><tr><td class="boldtd"><span>'.t('Sleeps:').'</span> ';
	$output .= strip_tags(drupal_render($form['spalm']));
	$output .='</td></tr><tr><td class="boldtd"><span>'.t('Class:').'</span>  ';
	$output .= strip_tags(drupal_render($form['class']));
	$output .='</td></tr><tr><td class="boldtd"><span>'.t('Floor:').'</span>  ';
	$output .= strip_tags(drupal_render($form['etaj']));
	$output .= '</td></tr><tr><td class="boldtd"><span>'.t('Levels:').'</span>  ';
	$output .= strip_tags(drupal_render($form['etajnost']));
	$output .= '</td></tr></table>';
	$output .='</div></div></fieldset>';
	$output .= '<fieldset class="date-zas">'.'<legend>'.t('Personal details').'</legend>';
	$output .= '<table><tr><td>';
	$output .= '<div class="personal_details">';
	$output .= '<table class="per_info"><tr><td>';
	$output .= drupal_render($form['popup_order_surname']);
	$output .= '</td></tr><tr><td>';
	$output .= drupal_render( $form['popup_order_name']);
	$output .= '</td></tr><tr><td>';
	$output .= drupal_render($form["email"]);
	$output.='</td></tr><tr><td>';
	$output .= drupal_render($form["phone"]); 
	$output .= '</td></tr></table></div></td><td>';
	$output .= '<div id="date_details">';
	$output .='<table class="date-table">'.'<tr>'.'<td>';
	$output .= drupal_render($form["date_zas"]);
	$output .= '</td>'.'</tr>'.'<tr>'.'<td>';
	$output .= drupal_render($form["date_vys"]);
	$output .= '</td>'.'</tr>'.'<tr>'.'<td>';
	$output .= drupal_render($form["hour_zas"]);
	$output .= '</td>'.'</tr>'.'<tr>'.'<td>';
	$output .= drupal_render($form["kolvo_zas"]);
	$output .= '</td>'.'</tr>'.'<tr>'.'<td>';
	$output .= drupal_render($form["children"]);
	$output .= '</td>'.'</tr>'.'<tr class="trdate">'.'<td>';
	$output .= drupal_render($form["transfer"]);
	$output .= '</td></tr></table></div></td></tr></table>';
$output .= '</fieldset>';
	$output.=drupal_render($form["other_info"]);
	$output .= '<div class="buttons">';
	$output .= drupal_render($form["submit"]);
	$output.= drupal_render($form["close"]);
	$output .='</div>';
	unset($form['prc']);
	$output .= drupal_render_children($form);
	// return the output
	return $output;

}


function popup_order_more_form_submit($form, &$form_state) {

$namevalid = trim($form_state['values']['popup_order_name']);
$surnamevalid = trim($form_state['values']['popup_order_surname']);

$params['counter']=$form_state['values']['counter'];
$params['name']= $form_state['values']['popup_order_name'];
$params['surname'] = $form_state['values']['popup_order_surname'];
$params['datazas'] = $form_state['values']['date_zas'];
$params['datavys'] = $form_state['values']['date_vys'];
$params['timezas'] = $form_state['values']['hour_zas'];
$params['idkvart'] = $form['idkvart']['#title'];

$day=$params['datazas'];
$day2 = $params['datavys'];
$countday = floor((strtotime($day2) -  strtotime($day)) / 86400);
$params['countday']= $countday;
$pr = strip_tags($form['prc']['#title']);
$pr = number_format($pr) * 1000;
$countprice = number_format(((strtotime($day2) -  strtotime($day)) / 86400)* $pr);
$params['price'] =  $countprice;
$params['kolvozas']= $form_state['values']['kolvo_zas'].' человек';
$params['transfer']= $form_state['values']['transfer']=='no'? $form_state['values']['transfer']='Нет не надо трансфер' : $form_state['values']['transfer']='Да надо встретить';
$params['phone']=$form_state['values']['phone'];
$params['other_info']=$form_state['values']['other_info'];
$email = $form_state['values']['email'];
$params['email']=$email;
$phonevalid=trim($form_state['values']['phone']);
if (isset($form['submit']['#value']) && $form_state['triggering_element']['#value'] == $form['submit']['#value'] 
&& valid_email_address($form_state['values']['email']) && !empty($form_state['values']['transfer']) && preg_match('/^[0-9()-xX\s]+$/', (string) $phonevalid) 
&& !empty($namevalid) && !empty($surnamevalid) && strlen($phonevalid) >= 7 )
{
  $to = 'office@mirkvartir.kz';
  $noreply='no-reply@mirkvartir.kz';
  $fromAndTo = $email;
  $lang = language_default();
  $send = TRUE;
$result=drupal_mail("popup_order", "admin", $to, $lang, $params, $noreply, $send);
$result1=drupal_mail("popup_order", "client", $fromAndTo, $lang, $params, $noreply, $send);
 if ($result['result'] == TRUE && $result1['result'] == TRUE) {
	drupal_set_message(t("It is successfully sent!"), 'status');
  }
  else {
  drupal_set_message(t("Error, please fill all fields correctly, this form not sent."), 'error');
  }
}
 }
function popup_order_mail($key, &$message, $params) {

  switch ($key) {
        case 'admin':
			$counter = $params['counter'];
			$name = $params['name'];
			$surname = $params ['surname'];
			$datazas = $params['datazas'];
			$datavys = $params['datavys'];
			$timezas = $params['timezas'];
			$kolvozas = $params['kolvozas'];
			$transfer = $params['transfer'];
			$id=$params['idkvart'];
			$price = $params['price'];

			$phone = $params['phone'];
			$other_info = $params['other_info'];
			$clientmail = $params['email'];
			$count =$params['countday'];
			
			$message['headers']['Content-Type'] = 'text/html; charset=UTF-8;';
            $message['subject'] .= check_plain("#{$counter} Заявка на бронирование ID квартиры #{$params['idkvart']}");
			$message['body'][] = '<html><body><style type="text/css"> .admintable {font-size: 18px;width:700px; margin:10px auto;}';
			$message['body'][] = ' tr:nth-child(odd) {background-color: #def;} tr:nth-child(even) { background-color: #fff;} .firsttd { font-weight: bold;} .admintable tr {height: 20px;}</style>';
			$message['body'][] = '<table class="admintable"><tr class="odd"><td class="firsttd">Номер заявки:</td><td><h4># '.$counter.'</h4></td></tr>';
			$message['body'][] = '<tr><td class="firsttd">ID квартиры:</td><td>'.$id.'</td></tr>';
			$message['body'][] = '<tr><td class="firsttd">Цена за '.$count.' дней:</td><td><h4>'.$price.' тенге</h4></td></tr>';
			$message['body'][] = '<tr><td class="firsttd">Имя:</td><td>'.$name.'</td></tr>';
			$message['body'][] = '<tr><td class="firsttd">Фамилия:</td><td>'.$surname.'</td></tr>';
			$message['body'][] = '<tr><td class="firsttd">Дата заселения:</td><td>'.$datazas.'</td></tr>';
			$message['body'][] = '<tr><td class="firsttd">Время заселения:</td><td>'.$timezas.'</td></tr>';
			$message['body'][] = '<tr><td class="firsttd">Дата выселения:</td><td>'.$datavys.'</td></tr>';
			$message['body'][] = '<tr><td class="firsttd">Кол-во заселяющихся:</td><td>'.$kolvozas.'</td></tr>';
			$message['body'][] = '<tr><td class="firsttd">Трансфер:</td><td>'.$transfer.'</td></tr>';
			$message['body'][] = '<tr><td class="firsttd">Контактный телефон:</td><td>'.$phone.'</td></tr>';
			$message['body'][] = '<tr><td class="firsttd">Контактный email:</td><td>'.$clientmail.'</td></tr>';
			$message['body'][] = '<tr><td class="firsttd">Дополнительная информация:</td><td>'.$other_info.'</td></tr>';
			$message['body'][] = '</table></body></html>';
		     break;
		case 'client':
			$counter = $params['counter'];
			$name = $params['name'];
			$surname = $params ['surname'];
			$datazas = $params['datazas'];
			$datavys = $params['datavys'];
			$timezas = $params['timezas'];
			$kolvozas = $params['kolvozas'];
			$id=$params['idkvart'];
			$transfer = $params['transfer'];
			$price = $params['prc'];
			$phone = $params['phone'];
			$other_info = $params['other_info'];
			$clientmail = $params['email'];
			$count =$params['countday'];
			
			
			$message['headers']['Content-Type'] = 'text/html; charset=UTF-8;';
            $message['subject'] .= check_plain("Бронирование квартиры на сайте www.mirkvartir.kz. Номер заказа  #{$counter} ");
			$message['body'][] = '<html><body><style type="text/css"> .body-wrap{ width:700px; margin:10px auto;}.admintable {font-size: 11pt; width:700px; margin:10px auto;}';
			$message['body'][] = 'tr:nth-child(odd) {background-color: #def;} tr:nth-child(even) { background-color: #fff;}.firsttd { font-weight: bold;} .admintable tr {height: 16px;}';
			$message['body'][] = '.first_data {font-size: 12pt; font-weight: bold;} .text { font-size: 12pt;} .second_data{font-size: 12pt;} .company {font-size: 12pt;}</style>';
			$message['body'][] = '<div class="body-wrap"><table><tr><td class="first_data">Уважаемый(ая)</td><td class="second_data">'.$surname.' '.$name.'</td></tr><tr><td class="first_data">Ваш номер заявки:</td><td class="second_data">#'.$counter.'</td></tr><tr><td class="first_data">ID квартиры</td><td class="second_data">'.$id.'</td></tr></table></br>';
			$message['body'][]= '</br><div><p class="text">Ваша заявка принята.</p> <p> Заявка будет рассмотрена в течении 4 часов. Если  данная квартира, которую Вы выбрали, на данный момент будет занята,</p><p> в этом случае мы можем предложить Вам альтернативный вариант. Заезд до 19:00 вечера. Возможность раннего заезда и позднего выезда заранее согласовывается.</p><p class="text"> В залог передается:</p> <ol><li>водительское удостоверение;</li><li>техпаспорт; <li>денежный залог;</li></ol> <p>Вы оставили следующие данные:</p></div>';
			$message['body'][] = '<table class="admintable">';
			$message['body'][] = '<tr><td class="firsttd">ID квартиры:</td><td>'.$id.'</td></tr>';
			$message['body'][] = '<tr><td class="firsttd">Дата заселения:</td><td>'.$datazas.'</td></tr>';
			$message['body'][] = '<tr><td class="firsttd">Время заселения:</td><td>'.$timezas.'</td></tr>';
			$message['body'][] = '<tr><td class="firsttd">Дата выселения:</td><td>'.$datavys.'</td></tr>';
			$message['body'][] = '<tr><td class="firsttd">Кол-во заселяющихся:</td><td>'.$kolvozas.'</td></tr>';
			$message['body'][] = '<tr><td class="firsttd">Трансфер:</td><td>'.$transfer.'</td></tr>';
			$message['body'][] = '<tr><td class="firsttd">Контактный телефон:</td><td>'.$phone.'</td></tr>';
			$message['body'][] = '<tr><td class="firsttd">Дополнительная информация:</td><td>'.$other_info.'</td></tr>';
			$message['body'][] = '<h3> Это сообщение СГЕНЕРИРОВАНО автоматический, не надо на него отвечать</h3>';
			$message['body'][] = '</table><p class="company">С уважением,  Компания "Мир Квартир" <br> Контакты: 8 (7172) 62-89-18, 8701 559 44 34 <br> email: office@mirkvartir.kz <br>  http://www.mirkvartir.kz</p></div></body></html>';
			break;
    }
}
function popup_order_element_info_alter(&$type) {
  if (isset($type['date_popup'])) {
    $type['date_popup']['#process'][] = 'popup_order_date_popup_process';
  }
}

function popup_order_date_popup_process($element, $form_state, $complete_form) {
  unset($element['date']['#description']);
  unset($element['date']['#title']);
  unset($element['time']['#title']);
  return $element;
}
